import { Tournament, GameMode, Announcement, HomeBanner, LeaderboardPlayer } from '../types';

export const INITIAL_MODES: Record<string, GameMode> = {
  mode_1: {
    id: 'mode_1',
    name: 'BR SURVIVAL',
    image: '/src/assets/images/mode_br_survival_1789014085300.jpg',
  },
  mode_2: {
    id: 'mode_2',
    name: 'BR KILLER',
    image: '/src/assets/images/mode_br_killer_1789014097979.jpg',
  },
  mode_3: {
    id: 'mode_3',
    name: 'CLASH SQU...',
    image: '/src/assets/images/mode_clash_squad_1789014111401.jpg',
  },
};

export const INITIAL_BANNERS: HomeBanner[] = [
  {
    id: 'b1',
    title: "TCM HP I'M ON LIVE",
    image: '/src/assets/images/ff_live_banner_1789014056388.jpg',
    link: 'liveStream',
    active: true,
    order: 1,
  },
  {
    id: 'b2',
    title: 'Grand Championship Season 7',
    image: '/src/assets/images/ff_br_banner_1789014071244.jpg',
    link: 'tournaments',
    active: true,
    order: 2,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'a1',
    title: 'Season 7 Live',
    message: 'Registrations are open for daily tournaments. Join and win cash rewards directly to your UPI.',
    active: true,
    order: 1,
    timestamp: Date.now() - 3600000,
  },
];

export const INITIAL_TOURNAMENTS: Record<string, Tournament> = {
  tourney_1: {
    id: 'tourney_1',
    name: 'Solo leveling',
    game: 'Free Fire',
    type: 'Solo',
    map: 'Bermuda',
    modeId: 'mode_1',
    modeName: 'BR SURVIVAL',
    entryFee: 5,
    prizePool: 5000,
    perKillPrize: 50,
    maxSlots: 50,
    filledSlots: 2,
    matchTime: new Date('2026-04-29T08:23:00').getTime(),
    status: 'upcoming',
    bannerUrl: '/src/assets/images/ff_br_banner_1789014071244.jpg',
    rules: '1. Teaming up is strictly prohibited.\n2. Room ID and password will be shared 15 minutes prior to match time.\n3. Take a screenshot of your result for dispute resolution.\n4. Emulators are disallowed unless specified.',
    visibility: 'public',
    createdAt: Date.now() - 100000,
    participants: {
      demo_user_1: {
        name: 'ViperX',
        gameName: 'ViperX_FF',
        gameUID: '748291038',
        joinedAt: Date.now() - 50000,
      },
      demo_user_2: {
        name: 'ShadowRogue',
        gameName: 'Shadow_99',
        gameUID: '839201948',
        joinedAt: Date.now() - 40000,
      },
    },
  },
  tourney_2: {
    id: 'tourney_2',
    name: 'Clash Squad 4v4 Showdown',
    game: 'Free Fire',
    type: 'Squad',
    map: 'Kalahari',
    modeId: 'mode_2',
    modeName: 'Clash Squad',
    entryFee: 50,
    prizePool: 1500,
    perKillPrize: 0,
    maxSlots: 16,
    filledSlots: 12,
    matchTime: Date.now() + 5 * 3600000,
    status: 'upcoming',
    bannerUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    rules: '1. Standard 4v4 Clash Squad rules.\n2. Weapon restrictions apply as per room config.\n3. Toxic behavior or abusing in voice chat leads to immediate disqualification.',
    visibility: 'public',
    createdAt: Date.now() - 90000,
  },
  tourney_3: {
    id: 'tourney_3',
    name: 'Pro Solo Kill Feast #98',
    game: 'Free Fire',
    type: 'Solo',
    map: 'Purgatory',
    modeId: 'mode_1',
    modeName: 'Battle Royale',
    entryFee: 30,
    prizePool: 1000,
    perKillPrize: 15,
    maxSlots: 48,
    filledSlots: 48,
    matchTime: Date.now() - 1800000,
    status: 'live',
    bannerUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80',
    rules: 'Live tournament in progress. Watch the stream via the center Live button.',
    visibility: 'public',
    createdAt: Date.now() - 200000,
  },
  tourney_4: {
    id: 'tourney_4',
    name: 'Mega Weekend Cup #95',
    game: 'Free Fire',
    type: 'Solo',
    map: 'Bermuda',
    modeId: 'mode_1',
    modeName: 'Battle Royale',
    entryFee: 25,
    prizePool: 800,
    perKillPrize: 12,
    maxSlots: 48,
    filledSlots: 48,
    matchTime: Date.now() - 86400000,
    status: 'completed',
    bannerUrl: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&auto=format&fit=crop&q=80',
    rules: 'Match concluded. Results and prizes distributed.',
    visibility: 'public',
    createdAt: Date.now() - 1000000,
    participants: {
      user_alpha: {
        name: 'ThunderKing',
        gameName: 'ThunderKing',
        gameUID: '109283741',
        joinedAt: Date.now() - 900000,
        rank: 1,
        kills: 8,
        prize: 350,
      },
      user_beta: {
        name: 'SniperQueen',
        gameName: 'SniperQueen',
        gameUID: '984729183',
        joinedAt: Date.now() - 890000,
        rank: 2,
        kills: 5,
        prize: 200,
      },
      user_gamma: {
        name: 'GhostRider',
        gameName: 'GhostRider',
        gameUID: '483920194',
        joinedAt: Date.now() - 880000,
        rank: 3,
        kills: 4,
        prize: 120,
      },
    },
  },
};

export const INITIAL_LEADERBOARD: LeaderboardPlayer[] = [
  {
    uid: 'lb_1',
    name: 'ThunderKing',
    img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    score: 4850,
    meta: '38 Wins | 142 Kills',
    rank: 1,
  },
  {
    uid: 'lb_2',
    name: 'SniperQueen',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    score: 3920,
    meta: '29 Wins | 118 Kills',
    rank: 2,
  },
  {
    uid: 'lb_3',
    name: 'GhostRider',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    score: 3210,
    meta: '24 Wins | 95 Kills',
    rank: 3,
  },
  {
    uid: 'lb_4',
    name: 'ApexPredator',
    img: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    score: 2840,
    meta: '19 Wins | 88 Kills',
    rank: 4,
  },
  {
    uid: 'lb_5',
    name: 'Valkyrie99',
    img: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    score: 2450,
    meta: '16 Wins | 73 Kills',
    rank: 5,
  },
  {
    uid: 'lb_6',
    name: 'BladeRunner',
    img: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    score: 2190,
    meta: '14 Wins | 65 Kills',
    rank: 6,
  },
];
